oc_props:
  host: "https://liander01.openshift.openline.nl:8443"
  token: "{{vault_token}}"
  validate_certs: False

application:
  instances: 1
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 1Gi
      cpu: 200m
